export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const PRODUCT_DELETE_REQUEST='PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS='PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_FAIL='PRODUCT_DELETE_FAIL';